//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilterStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilterStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Column.
        /// </summary>
        public static string addColumnButton {
            get {
                return ResourceManager.GetString("addColumnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new filter.
        /// </summary>
        public static string addNewFilterLabel {
            get {
                return ResourceManager.GetString("addNewFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row.
        /// </summary>
        public static string addRowButton {
            get {
                return ResourceManager.GetString("addRowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Matrix Filter.
        /// </summary>
        public static string basicMatrixFilterLabel {
            get {
                return ResourceManager.GetString("basicMatrixFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Control.
        /// </summary>
        public static string contentControlLabel {
            get {
                return ResourceManager.GetString("contentControlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new project.
        /// </summary>
        public static string createNewProjectLabel {
            get {
                return ResourceManager.GetString("createNewProjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute / Cancel.
        /// </summary>
        public static string executeButton {
            get {
                return ResourceManager.GetString("executeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string fileLabel {
            get {
                return ResourceManager.GetString("fileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Height.
        /// </summary>
        public static string filterHeightLabel {
            get {
                return ResourceManager.GetString("filterHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Width.
        /// </summary>
        public static string filterWidthLabel {
            get {
                return ResourceManager.GetString("filterWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussian Filter.
        /// </summary>
        public static string gaussianFilterLabel {
            get {
                return ResourceManager.GetString("gaussianFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscale Filter.
        /// </summary>
        public static string grayscaleFilterLabel {
            get {
                return ResourceManager.GetString("grayscaleFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string imageLabel {
            get {
                return ResourceManager.GetString("imageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Image.
        /// </summary>
        public static string inputImageLabel {
            get {
                return ResourceManager.GetString("inputImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Update.
        /// </summary>
        public static string liveUpdateLabel {
            get {
                return ResourceManager.GetString("liveUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load image.
        /// </summary>
        public static string loadImageLabel {
            get {
                return ResourceManager.GetString("loadImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project.
        /// </summary>
        public static string openProjectLabel {
            get {
                return ResourceManager.GetString("openProjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string optionsLabel {
            get {
                return ResourceManager.GetString("optionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Image.
        /// </summary>
        public static string outputImageLabel {
            get {
                return ResourceManager.GetString("outputImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string projectLabel {
            get {
                return ResourceManager.GetString("projectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project View.
        /// </summary>
        public static string projectViewLabel {
            get {
                return ResourceManager.GetString("projectViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Column.
        /// </summary>
        public static string removeColumnButton {
            get {
                return ResourceManager.GetString("removeColumnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Row.
        /// </summary>
        public static string removeRowButton {
            get {
                return ResourceManager.GetString("removeRowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected filter.
        /// </summary>
        public static string removeSelectedFilterLabel {
            get {
                return ResourceManager.GetString("removeSelectedFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save image.
        /// </summary>
        public static string saveImageLabel {
            get {
                return ResourceManager.GetString("saveImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        public static string saveProjectLabel {
            get {
                return ResourceManager.GetString("saveProjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigma.
        /// </summary>
        public static string sigmaLabel {
            get {
                return ResourceManager.GetString("sigmaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing.
        /// </summary>
        public static string statusBar1Label {
            get {
                return ResourceManager.GetString("statusBar1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string statusBar2Label {
            get {
                return ResourceManager.GetString("statusBar2Label", resourceCulture);
            }
        }
    }
}
