name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test FilterLib
      working-directory: FilterLib.Tests/
      run: dotnet test --no-restore --verbosity normal
    - name: Test FilterStudio
      working-directory: FilterStudio.Tests/
      run: dotnet test --no-restore --verbosity normal
